version: "3"

services:
  mlflow-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    # image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/${ARTIFACT_REGISTRY}/${IMAGE_NAME}:${TAG}

    ports:
      - "${PORT:-5001}:5000"
    volumes:
      - ${SERVICE_ACCOUNT_PATH:-/dev/null}:/app/service_account.json:ro # Mount service account if provided
    environment:
      - MLFLOW_TRACKING_URI
      - GOOGLE_APPLICATION_CREDENTIALS
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    networks:
      - ml-network

networks:
  ml-network:
    driver: bridge
# docker-compose up -d
# docker-compose logs -f
# docker-compose down -v
# rm -rf mlruns/*
# rm -rf models/*
