ml_config:
  input_data_path: "gs://aircheck-ml-ready/S202309/WDR91.tsv.gz" 
  columns_of_interest:
    - ECFP4
  target_col: Label
  is_binarized_data: True
  cluster_generation: True
  model_name: WDR91_bECFP4_Final
  processed_file_location: gs://test-aircheck/mlops-test/process_final.yaml
  smile_location: gs://enamine-vs/dataset/
  result_output: gs://test-aircheck/mlops-test/enamine_WDR91.smi
  isdry_run: False
  

  # docker cp ml-scripts-mlflow-app-1:/app/data/processed/sample_enamin_subset.smi .

