ml_config:
  # input_data_path: "gs://aircheck-ml-ready/S202309/WDR91.tsv.gz" 
  input_data_path: "gs://test-aircheck/mlops-test/subset_WDR91" 
  # input_data_path: "./data/raw/subset_WDR91"
  columns_of_interest:
    - ECFP4
  target_col: Label
  is_binarized_data: True
  cluster_generation: True
  model_name: WDR91_ECFP4-test-vertex
  # processed_file_location: "./processed_files/processed_data_dictionary.yaml"
  processed_file_location: gs://test-aircheck/mlops-test/process_final_vertexaitest12.yaml
  # smile_location: ./data/smiles/mcule_purchasable_full_241101.smi
  # smile_location: "./data/smiles/dataset_xaa_enamine_dataset.csv"
  # result_output: "./data/processed/sample_enamin_subset.smi"
  isdry_run: True
  smile_location: gs://enamine-vs/dataset/
  result_output: gs://test-aircheck/mlops-test/enamine_WDR91_test_mp.smi
  model_save_directory: "/app/models"
  
  

  # docker cp ml-scripts-mlflow-app-1:/app/data/processed/sample_enamin_subset.smi .

